# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
