# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170424_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='pollcategory',
            name='question',
            field=models.ManyToManyField(to='polls.Question'),
        ),
    ]
